version: '3.1'
services:
  web: &web
    build: .
    command: bundle exec rackup -o 0.0.0.0
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=mysql2://user:password@mysql/database
    volumes:
      - ./:/app
    ports:
      - 9292:9292
    depends_on:
      - redis
      - mysql
  worker:
    <<: *web
    command: bundle exec sidekiq -r ./worker.rb
    ports: []

  redis:
    image: redis:3.2.8-alpine

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
