version: '3.1'
services:
  web: &web
    image: mtsmfm/sidekiq-example
    command: bundle exec rackup -o 0.0.0.0
    environment:
      - REDIS_URL=redis://redis
    ports:
      - 9292:9292
    depends_on:
      - redis
  worker:
    <<: *web
    command: bundle exec sidekiq -r ./worker.rb
    ports: []

  redis:
    image: redis:3.2.8-alpine

volumes:
  bundle:
